"""enums added

Revision ID: 61c8b0b4a333
Revises: c3c0032b0240
Create Date: 2026-04-21 12:49:51.559817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c8b0b4a333'
down_revision: Union[str, Sequence[str], None] = 'c3c0032b0240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enum_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('enum_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enum_type_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enum_type_id'], ['enum_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_enum_values',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('enum_value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enum_value_id'], ['enum_values.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('position_id', 'enum_value_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_enum_values')
    op.drop_table('enum_values')
    op.drop_table('enum_types')
    # ### end Alembic commands ###
