"""init

Revision ID: 661dda824856
Revises: 
Create Date: 2026-04-21 11:42:01.023921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '661dda824856'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('positions', sa.Column('weight_unit_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_positions_weight_unit_id'), 'positions', ['weight_unit_id'], unique=False)
    op.create_foreign_key(None, 'positions', 'units', ['weight_unit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_index(op.f('ix_positions_weight_unit_id'), table_name='positions')
    op.drop_column('positions', 'weight_unit_id')
    op.drop_table('units')
    # ### end Alembic commands ###
